products:
  - id: "basreng-daun-jeruk"
    title: "Basreng Daun Jeruk"
    detail_produk: 
      - jenis_kemasan: "Standing Pouch"
        harga_jual: "Rp. 20.000"
        berat: "120-150gr"
        img: "basreng-pouch.jpg"
      - jenis_kemasan: "Toples Tabung 1 Liter"
        harga_jual: "Rp. 35.000"
        berat: "200-250gr"
        img: "basreng-toples1000ml.jpg"
    varian: 
      - varian_name: "Ikan"
      - varian_name: "Daging Kombinasi Ayam & Sapi"

  - id: "rengginang"
    title: "Rengginang"
    detail_produk:
      - jenis_kemasan: "Toples 10L"
        harga_jual: "Rp. 75.000"
        berat: "20 Butir"
        img: "rengginang-toples.jpg"
      - jenis_kemasan: "Plastik PE"
        harga_jual: "Rp. 60.000"
        berat: "10 Butir"
        img: "rengginang-kemasan.jpg"
      - jenis_kemasan: "Plastik PP Bening"
        harga_jual: "Rp. 6.000"
        berat: "2 Butir"
        img: "rengginang-ecer.jpg"
    varian: 
      - varian_name: "Terasi"
      - varian_name: "Original (Ketan Putih)"
      - varian_name: "Ketan Hitam"
