banners:
  - title: Toko Kami
    img: toko.webp
    weight: 150gr
    url: /store/
  - title: Testimoni Pelanggan
    img: testimoni.webp
    url: /testi/
  - title: Katalog Produk
    img: katalog.webp
    url: https://wa.me/c/6285172211985
  - title: Kontak Kami
    img: kontak.webp
    url: https://wa.me/6285172211985
  - title: Aplikasi Android
    img: aplikasi.webp
    url: https://dapoerela85.github.io/assets/app/DapoerEla85.apk
