banners:
  - title: Toko Kami
    img: toko.png
    weight: 150gr
    url: /store/
  - title: Testimoni Pelanggan
    img: testimoni.png
    url: /testimonies/
  - title: Katalog Produk
    img: katalog.png
    url: https://wa.me/c/6285172211985
